project_id = "ybxkehyomcakqjvuhnna"

[functions.admin-invite-manage]
verify_jwt = true

[functions.lookup-user-by-email]
verify_jwt = true

[functions.secure-site-access]
verify_jwt = false

[functions.secure-site-access-check]
verify_jwt = false

[functions.invite-request]
verify_jwt = false

[functions.cleanup-open-to-play]
verify_jwt = false

