import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.2';


const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const url = new URL(req.url);
    const analysisId = url.searchParams.get('analysisId');

    if (!analysisId) {
      return new Response('Missing analysisId parameter', {
        status: 400,
        headers: corsHeaders,
      });
    }

    // Authenticate user
    const authHeader = req.headers.get('authorization');
    if (!authHeader) {
      return new Response('Unauthorized', {
        status: 401,
        headers: corsHeaders,
      });
    }

    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    
    if (authError || !user) {
      return new Response('Invalid token', {
        status: 401,
        headers: corsHeaders,
      });
    }

    // Verify ownership and get analysis info
    const { data: analysis, error: analysisError } = await supabase
      .from('pro_ai_analyses')
      .select('created_at, swing_context, session_id')
      .eq('id', analysisId)
      .eq('user_id', user.id)
      .single();

    if (analysisError || !analysis) {
      return new Response('Analysis not found', {
        status: 404,
        headers: corsHeaders,
      });
    }

    // Get visuals for the analysis
    const { data: visuals, error } = await supabase
      .from('swing_visuals')
      .select('*')
      .eq('analysis_id', analysisId)
      .order('frame_index');

    if (error || !visuals || visuals.length === 0) {
      return new Response('No visuals found for analysis', {
        status: 404,
        headers: corsHeaders,
      });
    }

    // Create ZIP content (simplified tar-like structure)
    const zipContent = await createSimpleZip(visuals, analysis);
    const date = new Date().toISOString().split('T')[0].replace(/-/g, '');

    return new Response(zipContent, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="Echo_Swing_Pack_${date}.zip"`,
      },
    });

  } catch (error) {
    console.error('Error in export function:', error);
    return new Response('Internal server error', {
      status: 500,
      headers: corsHeaders,
    });
  }
});

async function createSimpleZip(visuals: any[], analysis: any): Promise<Uint8Array> {
  const phaseMap: Record<string, { order: number; name: string }> = {
    setup: { order: 1, name: 'P1_Setup' },
    takeaway: { order: 2, name: 'P2_Takeaway' },
    backswing: { order: 3, name: 'P3_Backswing' },
    top: { order: 4, name: 'P4_Top' },
    downswing: { order: 5, name: 'P5_Downswing' },
    impact: { order: 6, name: 'P6_Impact' },
    followThrough: { order: 7, name: 'P7_Follow_Through' }
  };

  // Create readme content
  const readmeContent = `Echo Swing Analysis Pack
========================

Analysis Date: ${analysis?.created_at ? new Date(analysis.created_at).toLocaleDateString() : 'Unknown'}
Context: ${analysis?.swing_context || 'Professional swing analysis'}

Visual Files:
${visuals.map((visual, index) => {
    const phase = phaseMap[visual.label] || { order: index + 1, name: visual.label };
    return `${String(phase.order).padStart(2, '0')}_${phase.name}.png - ${visual.overlay?.caption || 'Swing position analysis'}`;
  }).join('\n')}

Instructions:
- Each image shows key positions in your swing with professional overlays
- Review the annotations to understand the technical feedback
- Use these visuals to practice and improve your swing mechanics

Generated by Echo Golf Coach
`;

  // For now, return a simple text file with visual URLs and descriptions
  // In production, this would create a proper ZIP with images
  let fullContent = readmeContent + '\n\nDirect Image URLs:\n';
  
  visuals.forEach((visual, index) => {
    const phase = phaseMap[visual.label] || { order: index + 1, name: visual.label };
    fullContent += `\n${String(phase.order).padStart(2, '0')}_${phase.name}.png:\n`;
    fullContent += `Caption: ${visual.overlay?.caption || 'Swing position analysis'}\n`;
    fullContent += `URL: ${visual.url}\n`;
  });

  return new TextEncoder().encode(fullContent);
}