/**
 * Fixed mock data fixtures for Design Review Mode
 * Ensures consistent screenshots and reproducible states
 */

import { NearbyGolfer } from '../nearby/types';
import { GameBeacon } from '../nearby/hooks/useGameBeacon';

export const REVIEW_SEED = 'design-review-2025';

export const FIXED_NEARBY_GOLFERS: NearbyGolfer[] = [
  {
    id: 'review-golfer-1',
    display_name: 'Sarah Mitchell',
    home_club: 'Royal Birkdale',
    avatar_url: '/images/mocks/avatars/anna_shaw.jpg',
    is_online: true,
    distance_km: 0.5,
    same_club: true,
    isOpenToPlay: true,
  },
  {
    id: 'review-golfer-2',
    display_name: 'James Cooper',
    home_club: 'Formby Golf Club',
    avatar_url: '/images/mocks/avatars/tom_slice.jpg',
    is_online: true,
    distance_km: 1.2,
    same_club: false,
    isOpenToPlay: true,
  },
  {
    id: 'review-golfer-3',
    display_name: 'Emma Watson',
    home_club: 'Wallasey Golf Club',
    avatar_url: '/images/mocks/avatars/mia_putts.jpg',
    is_online: true,
    distance_km: 2.0,
    same_club: true,
    isOpenToPlay: false,
  },
  {
    id: 'review-golfer-4',
    display_name: 'Michael Brown',
    home_club: 'Hillside Golf Club',
    avatar_url: '/images/mocks/avatars/ben_holmes.jpg',
    is_online: true,
    distance_km: 0.8,
    same_club: false,
    isOpenToPlay: false,
  },
  {
    id: 'review-golfer-5',
    display_name: 'David Roberts',
    home_club: 'Royal Liverpool',
    avatar_url: '/images/mocks/avatars/classic_golf_pro.jpg',
    is_online: true,
    distance_km: 3.5,
    same_club: false,
    isOpenToPlay: true,
  },
];

export const FIXED_GAME_BEACONS: GameBeacon[] = [
  {
    id: 'review-beacon-1',
    host_user_id: 'review-host-1',
    host_profile: {
      id: 'review-host-1',
      display_name: 'Alex Thompson',
      avatar_url: '/images/mocks/avatars/anna_shaw.jpg',
      home_club: 'Royal Birkdale',
      eg_handicap_index: 12.5,
    },
    game_type: '18_holes',
    course_name: 'Royal Birkdale',
    note: '2 spots open, casual round, all levels welcome',
    start_time: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    tee_time: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    slots_total: 4,
    slots_open: 2,
    tagged_players: [],
    distance_km: 0.3,
    same_club_as_viewer: true,
    is_open_to_play: true,
  },
  {
    id: 'review-beacon-2',
    host_user_id: 'review-host-2',
    host_profile: {
      id: 'review-host-2',
      display_name: 'Sophie Martinez',
      avatar_url: '/images/mocks/avatars/mia_putts.jpg',
      home_club: 'Formby Golf Club',
      eg_handicap_index: 8.2,
    },
    game_type: '9_holes',
    course_name: 'Formby Golf Club',
    note: 'Quick 9 before sunset',
    start_time: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    tee_time: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    slots_total: 2,
    slots_open: 1,
    tagged_players: [],
    distance_km: 1.8,
    same_club_as_viewer: false,
    is_open_to_play: true,
  },
  {
    id: 'review-beacon-3',
    host_user_id: 'review-host-3',
    host_profile: {
      id: 'review-host-3',
      display_name: 'Tom Anderson',
      avatar_url: '/images/mocks/avatars/tom_slice.jpg',
      home_club: 'Hillside Golf Club',
      eg_handicap_index: 15.7,
    },
    game_type: 'practice',
    course_name: 'Hillside Golf Club',
    note: 'Range session then 9 holes',
    start_time: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    tee_time: new Date(Date.now() + 60 * 60 * 1000).toISOString(),
    expires_at: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
    slots_total: 3,
    slots_open: 3,
    tagged_players: [],
    distance_km: 2.5,
    same_club_as_viewer: false,
    is_open_to_play: false,
  },
];

export const FIXED_MY_BEACON: GameBeacon = {
  id: 'review-my-beacon',
  host_user_id: 'current-user',
  host_profile: {
    id: 'current-user',
    display_name: 'You',
    avatar_url: '/images/mocks/avatars/ben_holmes.jpg',
    home_club: 'Royal Birkdale',
    eg_handicap_index: 10.5,
  },
  game_type: '18_holes',
  course_name: 'Royal Birkdale',
  note: 'Looking for 2 players, friendly game',
  start_time: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
  tee_time: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
  expires_at: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
  created_at: new Date().toISOString(),
  slots_total: 4,
  slots_open: 2,
  tagged_players: [],
  distance_km: 0,
  same_club_as_viewer: true,
  is_open_to_play: true,
};
