-- The D3 shapes now live in tests/sql/explore_stream_d1_fixture.sql.
--
-- top100_lists and course_top100_memberships moved there because board_pool -
-- part of the DEPLOYED standing family the D1 fixture installs (audit ruling 3)
-- - references course_top100_memberships, and PostgreSQL validates a SQL
-- function body at CREATE time. Loading the tables afterwards was too late.
--
-- This file is retained, and still loaded by every harness script, so an older
-- checkout and any external caller keep working. Nothing to do here.
