
-- Insert GB&I courses ranked 31-60
INSERT INTO public.golf_courses (name, country, region, continent, regional_rank, description) VALUES
('West Sussex Golf Club', 'United Kingdom', 'Sussex', 'Europe', 31, 'West Sussex Golf Club is one of our favourite inland courses. It is sheer delight to play golf on this charming sandy outcrop of heathland.'),
('Rye Golf Club (Old)', 'United Kingdom', 'Sussex', 'Europe', 32, 'Rye Golf Club was founded in 1894 and was the inaugural design of 25-year-old Harry Colt. It''s one of the toughest courses in Britain.'),
('Woodhall Spa Golf Club (Hotchkin)', 'United Kingdom', 'Lincolnshire', 'Europe', 33, 'An oasis in the heart of Lincolnshire, this heathland course is a joy to play, set among glorious pine, birch and broom.'),
('Royal Troon Golf Club (Old)', 'United Kingdom', 'Ayrshire & Arran', 'Europe', 34, 'A traditional out-and-back links course on the Open Rota, best known for the short par-3 Postage Stamp and strategic Railway hole.'),
('Royal West Norfolk Golf Club', 'United Kingdom', 'Norfolk', 'Europe', 35, 'Located on a narrow strip of land, it becomes an island at high tide. A uniquely remote and natural golf experience.'),
('Walton Heath Golf Club (Old)', 'United Kingdom', 'Surrey', 'Europe', 36, 'Where inland golf feels like links — a classic course without the sea breeze, but full of challenge and charm.'),
('Machrihanish Golf Club (Championship)', 'United Kingdom', 'Argyll & Bute', 'Europe', 37, 'A romantic and natural layout on Scotland''s west coast. Short in length but rich in charm and fun.'),
('Royal Liverpool Golf Club', 'United Kingdom', 'Cheshire', 'Europe', 38, 'A challenging links exposed to Hoylake''s winds, with only a few holes nestled in dunes.'),
('Gleneagles (King''s)', 'United Kingdom', 'Perth & Kinross', 'Europe', 39, 'Possibly the best moorland course in the world, Gleneagles King''s offers breathtaking scenery and championship conditions.'),
('Loch Lomond Golf Club', 'United Kingdom', 'Dunbartonshire', 'Europe', 40, 'Nestled between mountain and loch, Loch Lomond is secluded and stunning, with over 600 acres of majestic landscape.'),
('Alwoodley Golf Club', 'United Kingdom', 'Yorkshire', 'Europe', 41, 'One of Britain''s finest and most subtle inland courses, located in a peaceful Yorkshire setting.'),
('European Club', 'Ireland', 'Wicklow', 'Europe', 42, 'Located between Wicklow and Arklow, this stunning Irish links sits on Ireland''s scenic east coast.'),
('Western Gailes Golf Club', 'United Kingdom', 'Ayrshire & Arran', 'Europe', 43, 'A varied, undulating links course interrupted by meandering burns and rich in character.'),
('Hollinwell', 'United Kingdom', 'Nottinghamshire', 'Europe', 44, 'Known as Notts Golf Club, this course is a secluded, high-quality heathland layout with a loyal following.'),
('Waterville Golf Links', 'Ireland', 'Kerry', 'Europe', 45, 'A remote, oceanfront links set on a spectacular promontory. Beautiful and challenging.'),
('Dumbarnie Links', 'United Kingdom', 'Fife', 'Europe', 46, 'A modern Clive Clark design with sweeping sea views, built on a historic Scottish estate.'),
('Silloth on Solway Golf Club', 'United Kingdom', 'Cumbria', 'Europe', 47, 'A remote and rewarding destination, full of rugged links character and charm.'),
('The Island', 'Ireland', 'Dublin', 'Europe', 48, 'A natural, unmanicured links in tune with its surroundings — raw and authentic.'),
('The Berkshire Golf Club (Red)', 'United Kingdom', 'Berkshire', 'Europe', 49, 'Forest, heather, and springy turf combine on this highly regarded inland course.'),
('County Louth Golf Club', 'Ireland', 'Louth', 'Europe', 50, 'Known locally as Baltray, this course welcomes you with its uplifting coastal approach road.'),
('Hillside Golf Club', 'United Kingdom', 'Lancashire', 'Europe', 51, 'An underrated gem near Royal Birkdale, divided only by a footpath but full of character.'),
('Formby Golf Club', 'United Kingdom', 'Lancashire', 'Europe', 52, 'A scenic blend of links and heathland, bordered on three sides by pine trees.'),
('Saunton Golf Club (East)', 'United Kingdom', 'Devon', 'Europe', 53, 'A potential future Open venue, this is a championship links of the highest standard.'),
('Nairn Golf Club (Championship)', 'United Kingdom', 'North Scotland', 'Europe', 54, 'A seaside course with views from every hole — one of Scotland''s most beautiful links.'),
('Wentworth Club (West)', 'United Kingdom', 'Surrey', 'Europe', 55, 'Home of the BMW PGA, Wentworth''s West course is Surrey''s best-known inland course.'),
('Hankley Common Golf Club', 'United Kingdom', 'Surrey', 'Europe', 56, 'A spacious heathland course with room to breathe and classic inland design.'),
('County Sligo Golf Club (Championship)', 'Ireland', 'Sligo', 'Europe', 57, 'Also known as Rosses Point, it''s a stirring links on the dramatic Irish west coast.'),
('Trump International Golf Links - Ireland', 'Ireland', 'Clare', 'Europe', 58, 'Once a Greg Norman creation, now redesigned by Martin Hawtree, and stunningly situated.'),
('Another Place, The Machrie', 'United Kingdom', 'Argyll & Bute', 'Europe', 59, 'Recently refurbished, this rugged links lies beside a boutique hotel on Islay.'),
('Adare Manor Golf Club', 'Ireland', 'Limerick', 'Europe', 60, 'A lavish parkland layout redesigned by Tom Fazio and home to the 2027 Ryder Cup.');
