
-- Update existing courses that may have different USA rankings
UPDATE public.golf_courses 
SET usa_rank = 1, description = 'Cypress Point stuns with dramatic coastal terrain where the Santa Lucia Mountains meet the Pacific. Every hole offers exhilarating elevation changes and panoramic ocean views.'
WHERE name = 'Cypress Point Club' AND country = 'United States';

UPDATE public.golf_courses 
SET usa_rank = 2, description = 'Pine Valley is George Crump''s legacy to the game—unforgiving, strategic, and brilliantly executed. Widely regarded as the pinnacle of penal golf architecture.'
WHERE name = 'Pine Valley Golf Club' AND country = 'United States';

UPDATE public.golf_courses 
SET usa_rank = 3, description = 'Shinnecock Hills holds a unique place in golf history, not only for its role in founding the USGA but also as the site of one of the first purpose-built clubhouses.'
WHERE name = 'Shinnecock Hills Golf Club' AND country = 'United States';

UPDATE public.golf_courses 
SET usa_rank = 4, description = 'National Golf Links of America is a masterpiece of early 20th-century design—part tribute, part benchmark for modern architects, and all classic charm.'
WHERE name = 'National Golf Links of America' AND country = 'United States';

UPDATE public.golf_courses 
SET usa_rank = 5, description = 'Oakmont is as brutal as it is brilliant. A beast of a course that''s hosted more majors than any in the U.S. outside Augusta—and tests the best every time.'
WHERE name = 'Oakmont Country Club' AND country = 'United States';

UPDATE public.golf_courses 
SET usa_rank = 6, description = 'Sand Hills offers a spiritual kind of golf—a course built on simplicity, natural design, and a proud resistance to commercial fanfare.'
WHERE name = 'Sand Hills Golf Club' AND country = 'United States';

UPDATE public.golf_courses 
SET usa_rank = 7, description = 'Merion may be old, but it''s far from outdated. This Philadelphia gem evolved from cricket-playing roots to host some of the game''s most storied moments.'
WHERE name = 'Merion Golf Club (East)' AND country = 'United States';

UPDATE public.golf_courses 
SET usa_rank = 8, description = 'Augusta National is where golf''s finest minds met perfection. Jones and MacKenzie created more than just a course—they created legend.'
WHERE name = 'Augusta National Golf Club' AND country = 'United States';

UPDATE public.golf_courses 
SET usa_rank = 9, description = 'Los Angeles Country Club''s North Course lives up to its postcode. Elegant, exclusive, and architecturally rich—it''s a course that matches its prestigious setting.'
WHERE name = 'Los Angeles Country Club (North)' AND country = 'United States';

UPDATE public.golf_courses 
SET usa_rank = 10, description = 'Fishers Island Club is a coastal gem—remote and romantic. Playing here feels like stepping into a time capsule lined with ocean spray.'
WHERE name = 'Fishers Island Club' AND country = 'United States';

-- Insert new courses that don't exist yet
INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image)
SELECT 'Friar''s Head', 'United States', 'New York', 'North America', 11, 'Friar''s Head is Coore and Crenshaw at their most creative. Carved from rugged land, this course champions freedom, imagination, and playability.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM public.golf_courses WHERE name = 'Friar''s Head' AND country = 'United States');

INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image)
SELECT 'Chicago Golf Club', 'United States', 'Illinois', 'North America', 12, 'Chicago Golf Club is steeped in legacy. One of America''s earliest clubs, and still one of its most elusive—tradition reigns supreme here.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM public.golf_courses WHERE name = 'Chicago Golf Club' AND country = 'United States');

INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image)
SELECT 'Bandon Dunes Golf Resort (Pacific Dunes)', 'United States', 'Oregon', 'North America', 13, 'Pacific Dunes is Tom Doak''s standout at Bandon—raw, rugged, and endlessly captivating. Many would argue it''s the best of the lot.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM public.golf_courses WHERE name = 'Bandon Dunes Golf Resort (Pacific Dunes)' AND country = 'United States');

INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image)
SELECT 'Pebble Beach Golf Links', 'United States', 'California', 'North America', 14, 'Pebble Beach is the accessible cousin to Cypress—every bit as scenic, with a history and layout that speaks for itself.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM public.golf_courses WHERE name = 'Pebble Beach Golf Links' AND country = 'United States');

INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image)
SELECT 'Prairie Dunes Country Club', 'United States', 'Kansas', 'North America', 15, 'Prairie Dunes surprises many. It''s Kansas, but it feels coastal. Inland links golf doesn''t get more authentic than this.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM public.golf_courses WHERE name = 'Prairie Dunes Country Club' AND country = 'United States');

INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image)
SELECT 'Riviera Country Club', 'United States', 'California', 'North America', 16, 'Riviera''s tight terrain and brilliant bunkering make it a rare gem. A strategic layout that gets better the more you play it.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM public.golf_courses WHERE name = 'Riviera Country Club' AND country = 'United States');

INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image)
SELECT 'Crystal Downs Country Club', 'United States', 'Michigan', 'North America', 17, 'Crystal Downs blends MacKenzie artistry with Midwest charm. A subtle headland course that rewards the observant and punishes the reckless.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM public.golf_courses WHERE name = 'Crystal Downs Country Club' AND country = 'United States');

INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image)
SELECT 'Winged Foot Golf Club (West)', 'United States', 'New York', 'North America', 18, 'Winged Foot (West) is Tillinghast at his finest—relentless, clever, and unforgiving. A true test of championship mettle.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM public.golf_courses WHERE name = 'Winged Foot Golf Club (West)' AND country = 'United States');

INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image)
SELECT 'California Golf Club of San Francisco', 'United States', 'California', 'North America', 19, 'Cal Club stretches out with purpose and punch. The modernised layout now plays long and tough, making it worthy of today''s top competitions.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM public.golf_courses WHERE name = 'California Golf Club of San Francisco' AND country = 'United States');

INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image)
SELECT 'Old Town Club', 'United States', 'North Carolina', 'North America', 20, 'Perry Maxwell''s design at Old Town Club showcases how undulating terrain can be transformed into a masterpiece. The steep swales and sharply contoured greens offer a thrilling challenge from start to finish.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM public.golf_courses WHERE name = 'Old Town Club' AND country = 'United States');

-- Continue with remaining courses (21-100) - will add them in batches to avoid overly long SQL
INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image) VALUES
('San Francisco Golf Club', 'United States', 'California', 'North America', 21, 'Crafted in 1915 by A.W. Tillinghast, San Francisco Golf Club is a true work of genius. Every hole is a testament to his architectural brilliance, wrapped in tradition and timeless design.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Somerset Hills Country Club', 'United States', 'New Jersey', 'North America', 22, 'Somerset Hills is a course of two contrasting natures: flat and open on the outward nine, then morphing into tight, wooded terrain on the inward holes—each with its own distinct charm.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Oakland Hills Country Club (South)', 'United States', 'Michigan', 'North America', 23, 'Oakland Hills'' South Course is steeped in championship history. With tree-lined fairways, formidable length, and six U.S. Opens under its belt, it''s a layout that demands both precision and power.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Camargo Club', 'United States', 'Ohio', 'North America', 24, 'Camargo Club, a Seth Raynor creation, is nestled in the rolling Ohio countryside. With its signature template holes and understated elegance, it''s one of America''s great hidden treasures.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Shoreacres', 'United States', 'Illinois', 'North America', 25, 'A visit to Shoreacres feels like stepping back into the golden age of golf. The David Adler-designed clubhouse and elegant layout combine to create a time-capsule experience.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('CapRock Ranch', 'United States', 'Nebraska', 'North America', 26, 'CapRock Ranch, perched in Nebraska''s sand hills, is the latest must-play destination for those chasing adventure and seclusion—golf here is rugged, remote and unforgettable.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Seminole Golf Club', 'United States', 'Florida', 'North America', 27, 'Located along Florida''s Atlantic coast, Seminole Golf Club is revered for its routing. The seamless way the course flows with the land is a masterclass in strategic architecture.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bethpage Black', 'United States', 'New York', 'North America', 28, 'Bethpage Black is as tough as they come. With its brutal slope rating, narrow fairways and thick rough, it''s not for the timid—this course is all about survival.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pinehurst No. 2', 'United States', 'North Carolina', 'North America', 29, 'Pinehurst No.2 is golf''s ultimate test of precision. Opened in 1907, its turtleback greens and subtle defenses define Donald Ross''s genius.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Oak Hill Country Club (East)', 'United States', 'New York', 'North America', 30, 'Oak Hill Country Club''s East Course is a major championship venue that commands respect. It''s widely considered one of America''s finest traditional parkland tests.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop');

-- Continue with courses 31-60
INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image) VALUES
('The Lido (Sand Valley)', 'United States', 'Wisconsin', 'North America', 31, 'C.B. Macdonald''s Lido Golf Course was a pre-war legend, blending Golden Age strategy with British links inspiration. Sadly lost to WWII, it remains a mythical giant of American golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Maidstone Club', 'United States', 'New York', 'North America', 32, 'Routed by Willie Park Jr., The Maidstone Club rolls across seaside dunes and delivers classic links golf on one of the finest natural sites in America.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Sleepy Hollow Country Club (Upper)', 'United States', 'New York', 'North America', 33, 'High above the Hudson River, Sleepy Hollow''s C.B. Macdonald and Seth Raynor layout combines grandeur with architectural nuance. Few settings match its historic presence.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Myopia Hunt Club', 'United States', 'Massachusetts', 'North America', 34, 'Founded in 1882, Myopia Hunt Club remains steeped in tradition. Its tight routing, tiny greens and quirky character make for an old-school challenge like no other.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Eastward Ho!', 'United States', 'Massachusetts', 'North America', 35, 'Eastward Ho! is Herbert Fowler''s American masterpiece. Routed over rugged coastal land, its dramatic elevation changes and sloping greens deliver breathtaking views and bold golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Garden City Golf Club', 'United States', 'New York', 'North America', 36, 'Garden City Golf Club is known for its elite exclusivity and classic layout—but its men-only policy has sparked as much attention as its strategic brilliance.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Ballyneal Golf Club', 'United States', 'Colorado', 'North America', 37, 'Ballyneal brings a touch of Ireland to the Colorado plains. This remote, wind-blown inland links channels the soul of the game in one of the most unique landscapes in America.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bandon Dunes Golf Resort (Bandon Trails)', 'United States', 'Oregon', 'North America', 38, 'Bandon Trails may be the third course at Bandon Dunes, but it''s no afterthought. Coore & Crenshaw''s routing through forest and dunes is as pure and engaging as golf gets.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bandon Dunes Golf Resort (Bandon Dunes)', 'United States', 'Oregon', 'North America', 39, 'Bandon Dunes set the standard for American links. Since 1999, its rugged fairways, fescue rough and ocean vistas have offered a truly authentic coastal golf experience.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Inverness Club', 'United States', 'Ohio', 'North America', 40, 'Despite the name, the Inverness Club has no monsters—just a brilliant Donald Ross design that has hosted majors and remains one of the Midwest''s elite golfing venues.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Rock Creek Cattle Company', 'United States', 'Montana', 'North America', 41, 'The Tom Doak-designed Rock Creek Cattle Company opened in 2008, with the dramatic Flint Creek Mountain Range framing the layout. It''s a remote Montana gem, rugged, natural, and unforgettable.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Whistling Straits (Straits Course)', 'United States', 'Wisconsin', 'North America', 42, 'Whistling Straits might look ancient, but its 560 acres were cleverly shaped by human hands into what now feels like a timeless links along the Lake Michigan shoreline.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Peachtree Golf Club', 'United States', 'Georgia', 'North America', 43, 'Peachtree Golf Club in Atlanta blends tradition and brilliance—co-designed by Bobby Jones and Robert Trent Jones, it reflects the soul of classic Southern golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Baltusrol Golf Club (Lower)', 'United States', 'New Jersey', 'North America', 44, 'Baltusrol Golf Club''s roots run deep, its name linked to Baltus Roll, the original landowner. The club''s historic significance is matched by the quality of its courses.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Kiawah Island Golf Resort (Ocean)', 'United States', 'South Carolina', 'North America', 45, 'Pete Dye''s Ocean Course at Kiawah Island is ferocious and breathtaking. With more seaside holes than any course in the Northern Hemisphere, it''s a bucket-list experience.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Country Club (Clyde & Squirrel)', 'United States', 'Massachusetts', 'North America', 46, 'The Country Club at Brookline may sound unassuming, but it was the first of its kind in the US. Its 27-hole layout, unified by Gil Hanse, remains truly iconic.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Old Barnwell', 'United States', 'South Carolina', 'North America', 47, 'Old Barnwell redefines private golf. Modern yet steeped in ethos, this South Carolina layout does things differently—with thoughtful routing and a mission-driven club culture.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Old Sandwich Golf Club', 'United States', 'Massachusetts', 'North America', 48, 'Old Sandwich''s green complexes are a true highlight—subtle contours and stunning bunker work by Jeff Bradley make this one of New England''s hidden masterpieces.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Essex County Club', 'United States', 'Massachusetts', 'North America', 49, 'Essex County Club''s par-5 3rd hole is a beast—nearly as long as the previous two combined, it proves that strategy and shape are as important as sheer distance.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Winged Foot Golf Club (East)', 'United States', 'New York', 'North America', 50, 'Winged Foot''s East Course is another A.W. Tillinghast classic. Strategic, timeless and brutally elegant—it''s every bit the equal of its famous West sibling.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Yeamans Hall Club', 'United States', 'South Carolina', 'North America', 51, 'Yeamans Hall Club, crafted by Seth Raynor in 1925, remains one of South Carolina''s most admired courses. Stepping onto its grounds feels like entering a time capsule.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Wade Hampton Golf Club', 'United States', 'North Carolina', 'North America', 52, 'Wade Hampton Golf Club, named after a 19th-century general, is now best known for its stunning mountain golf and masterful design—pure Carolina perfection.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Southern Hills Country Club (Championship)', 'United States', 'Oklahoma', 'North America', 53, 'Southern Hills exudes tradition. Gil Hanse''s updates have only enhanced its tough, tree-lined aesthetic and famously punishing Bermuda rough.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Ohoopee Match Club', 'United States', 'Georgia', 'North America', 54, 'Ohoopee Match Club is minimalist magic. Set in rural Georgia on a former onion farm, its match-play focus and intimate scale make it wholly unique.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Golf Club', 'United States', 'Ohio', 'North America', 55, 'Pete Dye''s early work at The Golf Club in New Albany, Ohio, reveals his genius in restraint. A mature layout with charm and challenge in equal measure.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Quaker Ridge Golf Club', 'United States', 'New York', 'North America', 56, 'Quaker Ridge Golf Club may fly under the radar, but insiders know it''s one of the best-kept secrets in American golf—superb routing and conditioning.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Piping Rock Club', 'United States', 'New York', 'North America', 57, 'Piping Rock, designed by C.B. Macdonald in 1911, competes with polo for attention on Long Island—but holds its own with an all-world set of template holes.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Gozzer Ranch Golf & Lake Club', 'United States', 'Idaho', 'North America', 58, 'Gozzer Ranch''s setting is jaw-dropping. Perched above Lake Coeur d''Alene, it combines drama, elevation, and lakeside beauty into one unforgettable package.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Shadow Creek', 'United States', 'Nevada', 'North America', 59, 'Shadow Creek is pure Las Vegas spectacle—Tom Fazio sculpted it from desert floor to create a lush, surreal golf oasis that''s now open to all.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Scioto Country Club', 'United States', 'Ohio', 'North America', 60, 'Scioto Country Club is where Jack Nicklaus grew up and learned the game—a historic, revered place with a proud legacy and strong Midwestern spirit.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop');

-- Continue with courses 61-100
INSERT INTO public.golf_courses (name, country, region, continent, usa_rank, description, thumbnail_image) VALUES
('Muirfield Village Golf Club', 'United States', 'Ohio', 'North America', 61, 'No expense was spared at Muirfield Village, and it shows. Jack Nicklaus''s vision includes water, tight fairways, and tournament-level conditioning throughout.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Plainfield Country Club', 'United States', 'New Jersey', 'North America', 62, 'Plainfield Country Club is far from plain. Donald Ross''s masterwork in New Jersey surprises many with its bold greens and thrilling, hilly terrain.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pasatiempo Golf Club', 'United States', 'California', 'North America', 63, 'Pasatiempo is vintage MacKenzie. Built in 1929, it''s got quirky charm, bold design, and a historic foursomes match to its name.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('White Bear Yacht Club', 'United States', 'Minnesota', 'North America', 64, 'White Bear Yacht Club tests your balance more than your distance. With almost no level lies, it''s a fascinating challenge requiring total control.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Monterey Peninsula Country Club (Dunes)', 'United States', 'California', 'North America', 65, 'The Dunes Course at Monterey Peninsula Country Club combines Raynor roots with MacKenzie tweaks and a modern Fazio revamp—history and progress in one.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('TPC Sawgrass (Stadium)', 'United States', 'Florida', 'North America', 66, 'TPC Sawgrass Stadium Course needs no introduction. The island green 17th has captured imaginations and shattered scorecards since 1980.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Valley Club of Montecito', 'United States', 'California', 'North America', 67, 'The Valley Club of Montecito is modest by MacKenzie standards, but its elegance and pace of play make it one of the West Coast''s most charming rounds.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Kittansett Club', 'United States', 'Massachusetts', 'North America', 68, 'The Kittansett Club''s windswept location on Buzzards Bay ensures every shot counts. Great design meets Mother Nature on this coastal New England gem.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Boston Golf Club', 'United States', 'Massachusetts', 'North America', 69, 'Boston Golf Club is routed across prime Massachusetts land. Brian Silva''s design is rugged, smart, and perfectly suited to private, pure golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Baltimore Country Club (East)', 'United States', 'Maryland', 'North America', 70, 'Baltimore CC''s East Course, designed by A.W. Tillinghast in 1926, holds true to classic architecture—historic, tough, and wonderfully tree-lined.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Milwaukee Country Club', 'United States', 'Wisconsin', 'North America', 71, 'Milwaukee Country Club is Wisconsin golf royalty. With origins dating to 1890, today''s course by Charles Hugh Alison remains a stern and scenic test.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Lawsonia Links', 'United States', 'Wisconsin', 'North America', 72, 'Lawsonia Links, built in 1930, is a Langford gem—bold shaping, clever bunkering, and a golden-age feel that punches well above its price tag.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Olympic Club (Lake)', 'United States', 'California', 'North America', 73, 'The Lake Course at Olympic Club is a major test. With a relentless slope and narrow fairways, it''s hosted four US Opens and deserves every one.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Nanea Golf Club', 'United States', 'Hawaii', 'North America', 74, 'Nanea Golf Club in Hawaii is ultra-private and volcano-born. British links principles meet lava rock for a one-of-a-kind golfing experience.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Sand Valley Golf Resort (Sand Valley)', 'United States', 'Wisconsin', 'North America', 75, 'Sand Valley is Keiser''s inland marvel. Set on ancient dunes in Wisconsin, it feels oceanside even without the sea—sand, width, and wind in spades.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Victoria National Golf Club', 'United States', 'Indiana', 'North America', 76, 'Carved from a reclaimed coal mine, Victoria National emerged in 1997 as a vision realised by Tom Fazio and founder Terry Friedman. It''s now one of Indiana''s standout layouts—bold, dramatic, and beautifully reimagined.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Congaree Golf Club', 'United States', 'South Carolina', 'North America', 77, 'A club unlike any other, Congaree combines elite course architecture with a purpose-driven mission. Built by two experienced private club owners, this South Carolina gem is philanthropic golf at its finest.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Creek Club', 'United States', 'New York', 'North America', 78, 'Designed by the legendary duo Charles Blair Macdonald and Seth Raynor, The Creek is a masterclass in early American course design, blending strategic brilliance with elegant shaping.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Calusa Pines Golf Club', 'United States', 'Florida', 'North America', 79, 'Calusa Pines is bold by design—quite literally. Tons of rock were removed to give this Naples, Florida course its rare elevation changes and thrilling visual drama.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('St Louis Country Club', 'United States', 'Missouri', 'North America', 80, 'Nestled just outside the city, Saint Louis Country Club dates back to 1914 and uses its compact site creatively, showcasing the architectural subtleties of its golden-era roots.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Ridgewood Country Club (East & West)', 'United States', 'New Jersey', 'North America', 81, 'Featuring three nine-hole loops—West, East, and Center—this club in New Jersey offers versatility and charm. The Clifford Wendehack-designed clubhouse adds historic appeal to a timeless layout.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bel-Air Country Club', 'United States', 'California', 'North America', 82, 'This George C. Thomas classic channels the glamour of the 1920s with routing that weaves through canyons and ridges. Tom Doak has called it one of the most extraordinary routings ever created.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Ladera Golf Club', 'United States', 'California', 'North America', 83, 'A minimalist contrast to nearby desert developments, this exclusive design by Gil Hanse and Jim Wagner delivers a natural, understated experience amid Palm Springs'' sculpted excess.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Honors Course', 'United States', 'Tennessee', 'North America', 84, 'Hidden in a lush valley north of Chattanooga, The Honors Course is a true Southern treasure—quietly exceptional and consistently ranked among the country''s best.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Colorado Golf Club', 'United States', 'Colorado', 'North America', 85, 'Opened in 2007, this Bill Coore and Ben Crenshaw design respects the game''s roots while embracing Colorado''s rolling terrain. It''s already considered a modern American classic.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Kingsley Club', 'United States', 'Michigan', 'North America', 86, 'Set in sandy Michigan terrain, Kingsley delivers a links-style feel far from the coast. Since opening in 2001, it has quietly built a cult following among design purists.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pikewood National Golf Club', 'United States', 'West Virginia', 'North America', 87, 'Built over years with no compromise, Pikewood is a true test of endurance and precision, winding through forested mountains on a challenging limestone landscape.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Tree Farm', 'United States', 'South Carolina', 'North America', 88, 'Born from Zac Blair''s passion for golf architecture, The Tree Farm is a modern community-focused club, designed as a place where golf lovers gather, play, and enjoy great design.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Lake Merced Golf Club', 'United States', 'California', 'North America', 89, 'This San Francisco-area course has been reshaped through the decades by MacKenzie, Graves, and Rees Jones—resulting in a course with deep architectural pedigree.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Old Elm Club', 'United States', 'Illinois', 'North America', 90, 'A collaboration between Harry Colt and Donald Ross, Old Elm is a rare blend of two great minds. Laid out in 1913, it remains a model of subtlety and traditional elegance.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Congressional Country Club (Blue)', 'United States', 'Maryland', 'North America', 91, 'Opened in 1924, this club near Washington, D.C. began with a straightforward layout by Devereux Emmet but evolved into one of America''s most recognisable tournament venues.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Scottsdale National Golf Club (The Other Course)', 'United States', 'Arizona', 'North America', 92, 'Jackson and Khan''s 15-month effort resulted in something boldly different. With unique features and views, this course challenges conventions in the Arizona desert.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Moraine Country Club', 'United States', 'Ohio', 'North America', 93, 'Originally laid out by Alec "Nipper" Campbell in 1930, Moraine was revitalised in 2015 by Keith Foster, restoring the rolling, golden-age design that makes it so special.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Lost Rail Golf Club', 'United States', 'Nebraska', 'North America', 94, 'Scott Hoffman and his cousin teamed up with Landscapes Unlimited to create Nebraska''s next big golf destination—designed to blend top-tier construction with Midwestern soul.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Streamsong Red', 'United States', 'Florida', 'North America', 95, 'Of all the holes at Streamsong, the Red''s short par-4 9th may be the most revered—especially by Tom Doak, who considers it one of his personal favourites.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Chambers Bay', 'United States', 'Washington', 'North America', 96, 'Opened in 2007, this Washington layout has already hosted a U.S. Open and continues to rise in esteem. Built on a reclaimed gravel mine, it''s rugged and visually striking.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Fox Chapel Golf Club', 'United States', 'Pennsylvania', 'North America', 97, 'A hidden gem in Pittsburgh, Fox Chapel is one of Seth Raynor''s most underappreciated works—a course full of bold strategy and template hole precision.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Sand Valley (Sedge Valley)', 'United States', 'Wisconsin', 'North America', 98, 'Tom Doak''s Sedge Valley pays homage to the heathlands of England. Shorter than its resort siblings, it''s full of charm, character, and creative shotmaking.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Medinah Country Club (No.3)', 'United States', 'Illinois', 'North America', 99, 'A Chicago institution since the 1920s, Medinah was born from a dream to be the finest club in the country. With multiple courses, it remains a pillar of American golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bandon Dunes Golf Resort (Old Macdonald)', 'United States', 'Oregon', 'North America', 100, 'Inspired by Charles Blair Macdonald''s design principles, Old Macdonald is the fourth course at Bandon Dunes—and a bold, open tribute to early American golf ideals.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop');

-- Handle potential conflicts by using ON CONFLICT DO NOTHING for bulk inserts
