
-- Insert USA Top 100 courses 1-72 (completing the interrupted migration)
INSERT INTO public.golf_courses (name, country, region, continent, global_rank, usa_rank, description, thumbnail_image) VALUES
-- Courses 1-10
('Cypress Point Club', 'United States', 'California', 'North America', 1, 1, 'Cypress Point stuns with dramatic coastal terrain where the Santa Lucia Mountains meet the Pacific. Every hole offers exhilarating elevation changes and panoramic ocean views.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pine Valley Golf Club', 'United States', 'New Jersey', 'North America', 2, 2, 'Pine Valley is George Crump''s legacy to the game—unforgiving, strategic, and brilliantly executed. Widely regarded as the pinnacle of penal golf architecture.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Shinnecock Hills Golf Club', 'United States', 'New York', 'North America', 4, 3, 'Shinnecock Hills holds a unique place in golf history, not only for its role in founding the USGA but also as the site of one of the first purpose-built clubhouses.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('National Golf Links of America', 'United States', 'New York', 'North America', 5, 4, 'National Golf Links of America is a masterpiece of early 20th-century design—part tribute, part benchmark for modern architects, and all classic charm.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Oakmont Country Club', 'United States', 'Pennsylvania', 'North America', 8, 5, 'Oakmont is as brutal as it is brilliant. A beast of a course that''s hosted more majors than any in the U.S. outside Augusta—and tests the best every time.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Sand Hills Golf Club', 'United States', 'Nebraska', 'North America', 11, 6, 'Sand Hills offers a spiritual kind of golf—a course built on simplicity, natural design, and a proud resistance to commercial fanfare.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Merion Golf Club (East)', 'United States', 'Pennsylvania', 'North America', 13, 7, 'Merion may be old, but it''s far from outdated. This Philadelphia gem evolved from cricket-playing roots to host some of the game''s most storied moments.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Augusta National Golf Club', 'United States', 'Georgia', 'North America', 16, 8, 'Augusta National is where golf''s finest minds met perfection. Jones and MacKenzie created more than just a course—they created legend.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Los Angeles Country Club (North)', 'United States', 'California', 'North America', 18, 9, 'Los Angeles Country Club''s North Course lives up to its postcode. Elegant, exclusive, and architecturally rich—it''s a course that matches its prestigious setting.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Fishers Island Club', 'United States', 'New York', 'North America', 20, 10, 'Fishers Island Club is a coastal gem—remote and romantic. Playing here feels like stepping into a time capsule lined with ocean spray.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),

-- Courses 11-20
('Friar''s Head', 'United States', 'New York', 'North America', 23, 11, 'Friar''s Head is Coore and Crenshaw at their most creative. Carved from rugged land, this course champions freedom, imagination, and playability.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Chicago Golf Club', 'United States', 'Illinois', 'North America', 24, 12, 'Chicago Golf Club is steeped in legacy. One of America''s earliest clubs, and still one of its most elusive—tradition reigns supreme here.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bandon Dunes Golf Resort (Pacific Dunes)', 'United States', 'Oregon', 'North America', 26, 13, 'Pacific Dunes is Tom Doak''s standout at Bandon—raw, rugged, and endlessly captivating. Many would argue it''s the best of the lot.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pebble Beach Golf Links', 'United States', 'California', 'North America', 27, 14, 'Pebble Beach is the accessible cousin to Cypress—every bit as scenic, with a history and layout that speaks for itself.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Prairie Dunes Country Club', 'United States', 'Kansas', 'North America', 28, 15, 'Prairie Dunes surprises many. It''s Kansas, but it feels coastal. Inland links golf doesn''t get more authentic than this.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Riviera Country Club', 'United States', 'California', 'North America', 30, 16, 'Riviera''s tight terrain and brilliant bunkering make it a rare gem. A strategic layout that gets better the more you play it.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Crystal Downs Country Club', 'United States', 'Michigan', 'North America', 31, 17, 'Crystal Downs blends MacKenzie artistry with Midwest charm. A subtle headland course that rewards the observant and punishes the reckless.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Winged Foot Golf Club (West)', 'United States', 'New York', 'North America', 33, 18, 'Winged Foot (West) is Tillinghast at his finest—relentless, clever, and unforgiving. A true test of championship mettle.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('California Golf Club of San Francisco (Cal Club)', 'United States', 'California', 'North America', 36, 19, 'Cal Club stretches out with purpose and punch. The modernised layout now plays long and tough, making it worthy of today''s top competitions.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Old Town Club', 'United States', 'North Carolina', 'North America', 38, 20, 'Perry Maxwell''s design at Old Town Club showcases how undulating terrain can be transformed into a masterpiece. The steep swales and sharply contoured greens offer a thrilling challenge from start to finish.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),

-- Courses 21-30
('San Francisco Golf Club', 'United States', 'California', 'North America', 39, 21, 'Crafted in 1915 by A.W. Tillinghast, San Francisco Golf Club is a true work of genius. Every hole is a testament to his architectural brilliance, wrapped in tradition and timeless design.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Somerset Hills Country Club', 'United States', 'New Jersey', 'North America', 40, 22, 'Somerset Hills is a course of two contrasting natures: flat and open on the outward nine, then morphing into tight, wooded terrain on the inward holes—each with its own distinct charm.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Oakland Hills Country Club (South)', 'United States', 'Michigan', 'North America', 46, 23, 'Oakland Hills'' South Course is steeped in championship history. With tree-lined fairways, formidable length, and six U.S. Opens under its belt, it''s a layout that demands both precision and power.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Camargo Club', 'United States', 'Ohio', 'North America', 48, 24, 'Camargo Club, a Seth Raynor creation, is nestled in the rolling Ohio countryside. With its signature template holes and understated elegance, it''s one of America''s great hidden treasures.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Shoreacres', 'United States', 'Illinois', 'North America', 51, 25, 'A visit to Shoreacres feels like stepping back into the golden age of golf. The David Adler-designed clubhouse and elegant layout combine to create a time-capsule experience.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('CapRock Ranch', 'United States', 'Nebraska', 'North America', 53, 26, 'CapRock Ranch, perched in Nebraska''s sand hills, is the latest must-play destination for those chasing adventure and seclusion—golf here is rugged, remote and unforgettable.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Seminole Golf Club', 'United States', 'Florida', 'North America', 55, 27, 'Located along Florida''s Atlantic coast, Seminole Golf Club is revered for its routing. The seamless way the course flows with the land is a masterclass in strategic architecture.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bethpage (Black)', 'United States', 'New York', 'North America', 58, 28, 'Bethpage Black is as tough as they come. With its brutal slope rating, narrow fairways and thick rough, it''s not for the timid—this course is all about survival.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pinehurst (No.2)', 'United States', 'North Carolina', 'North America', 57, 29, 'Pinehurst No.2 is golf''s ultimate test of precision. Opened in 1907, its turtleback greens and subtle defenses define Donald Ross''s genius.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Oak Hill Country Club (East)', 'United States', 'New York', 'North America', 59, 30, 'Oak Hill Country Club''s East Course is a major championship venue that commands respect. It''s widely considered one of America''s finest traditional parkland tests.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),

-- Courses 31-40
('The Lido Golf Club (Sand Valley)', 'United States', 'Wisconsin', 'North America', 60, 31, 'C.B. Macdonald''s Lido Golf Course was a pre-war legend, blending Golden Age strategy with British links inspiration. Sadly lost to WWII, it remains a mythical giant of American golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Maidstone Club', 'United States', 'New York', 'North America', 62, 32, 'Routed by Willie Park Jr., The Maidstone Club rolls across seaside dunes and delivers classic links golf on one of the finest natural sites in America.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Sleepy Hollow Country Club (Upper)', 'United States', 'New York', 'North America', 66, 33, 'High above the Hudson River, Sleepy Hollow''s C.B. Macdonald and Seth Raynor layout combines grandeur with architectural nuance. Few settings match its historic presence.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Myopia Hunt Club', 'United States', 'Massachusetts', 'North America', 67, 34, 'Founded in 1882, Myopia Hunt Club remains steeped in tradition. Its tight routing, tiny greens and quirky character make for an old-school challenge like no other.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Eastward Ho!', 'United States', 'Massachusetts', 'North America', 71, 35, 'Eastward Ho! is Herbert Fowler''s American masterpiece. Routed over rugged coastal land, its dramatic elevation changes and sloping greens deliver breathtaking views and bold golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Garden City Golf Club', 'United States', 'New York', 'North America', 75, 36, 'Garden City Golf Club is known for its elite exclusivity and classic layout—but its men-only policy has sparked as much attention as its strategic brilliance.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Ballyneal Golf Club', 'United States', 'Colorado', 'North America', 76, 37, 'Ballyneal brings a touch of Ireland to the Colorado plains. This remote, wind-blown inland links channels the soul of the game in one of the most unique landscapes in America.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bandon Dunes Golf Resort (Bandon Trails)', 'United States', 'Oregon', 'North America', 78, 38, 'Bandon Trails may be the third course at Bandon Dunes, but it''s no afterthought. Coore & Crenshaw''s routing through forest and dunes is as pure and engaging as golf gets.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bandon Dunes Golf Resort (Bandon Dunes)', 'United States', 'Oregon', 'North America', 79, 39, 'Bandon Dunes set the standard for American links. Since 1999, its rugged fairways, fescue rough and ocean vistas have offered a truly authentic coastal golf experience.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Inverness Club', 'United States', 'Ohio', 'North America', 81, 40, 'Despite the name, the Inverness Club has no monsters—just a brilliant Donald Ross design that has hosted majors and remains one of the Midwest''s elite golfing venues.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),

-- Courses 41-50
('Rock Creek Cattle Company', 'United States', 'Montana', 'North America', 83, 41, 'The Tom Doak-designed Rock Creek Cattle Company opened in 2008, with the dramatic Flint Creek Mountain Range framing the layout. It''s a remote Montana gem, rugged, natural, and unforgettable.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Whistling Straits - Straits Course', 'United States', 'Wisconsin', 'North America', 87, 42, 'Whistling Straits might look ancient, but its 560 acres were cleverly shaped by human hands into what now feels like a timeless links along the Lake Michigan shoreline.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Peachtree', 'United States', 'Georgia', 'North America', 94, 43, 'Peachtree Golf Club in Atlanta blends tradition and brilliance—co-designed by Bobby Jones and Robert Trent Jones, it reflects the soul of classic Southern golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Baltusrol Golf Club (Lower)', 'United States', 'New Jersey', 'North America', NULL, 44, 'Baltusrol Golf Club''s roots run deep, its name linked to Baltus Roll, the original landowner. The club''s historic significance is matched by the quality of its courses.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Kiawah Island Golf Resort (Ocean)', 'United States', 'South Carolina', 'North America', NULL, 45, 'Pete Dye''s Ocean Course at Kiawah Island is ferocious and breathtaking. With more seaside holes than any course in the Northern Hemisphere, it''s a bucket-list experience.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Country Club (Clyde & Squirrel)', 'United States', 'Massachusetts', 'North America', NULL, 46, 'The Country Club at Brookline may sound unassuming, but it was the first of its kind in the US. Its 27-hole layout, unified by Gil Hanse, remains truly iconic.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Old Barnwell', 'United States', 'South Carolina', 'North America', NULL, 47, 'Old Barnwell redefines private golf. Modern yet steeped in ethos, this South Carolina layout does things differently—with thoughtful routing and a mission-driven club culture.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Old Sandwich Golf Club', 'United States', 'Massachusetts', 'North America', NULL, 48, 'Old Sandwich''s green complexes are a true highlight—subtle contours and stunning bunker work by Jeff Bradley make this one of New England''s hidden masterpieces.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Essex County Club', 'United States', 'Massachusetts', 'North America', NULL, 49, 'Essex County Club''s par-5 3rd hole is a beast—nearly as long as the previous two combined, it proves that strategy and shape are as important as sheer distance.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Winged Foot Golf Club (East)', 'United States', 'New York', 'North America', NULL, 50, 'Winged Foot''s East Course is another A.W. Tillinghast classic. Strategic, timeless and brutally elegant—it''s every bit the equal of its famous West sibling.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),

-- Courses 51-60
('Yeamans Hall Club', 'United States', 'South Carolina', 'North America', NULL, 51, 'Yeamans Hall Club, crafted by Seth Raynor in 1925, remains one of South Carolina''s most admired courses. Stepping onto its grounds feels like entering a time capsule.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Wade Hampton Golf Club', 'United States', 'North Carolina', 'North America', NULL, 52, 'Wade Hampton Golf Club, named after a 19th-century general, is now best known for its stunning mountain golf and masterful design—pure Carolina perfection.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Southern Hills Country Club (Championship)', 'United States', 'Oklahoma', 'North America', NULL, 53, 'Southern Hills exudes tradition. Gil Hanse''s updates have only enhanced its tough, tree-lined aesthetic and famously punishing Bermuda rough.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Ohoopee Match Club', 'United States', 'Georgia', 'North America', NULL, 54, 'Ohoopee Match Club is minimalist magic. Set in rural Georgia on a former onion farm, its match-play focus and intimate scale make it wholly unique.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Golf Club', 'United States', 'Ohio', 'North America', NULL, 55, 'Pete Dye''s early work at The Golf Club in New Albany, Ohio, reveals his genius in restraint. A mature layout with charm and challenge in equal measure.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Quaker Ridge Golf Club', 'United States', 'New York', 'North America', NULL, 56, 'Quaker Ridge Golf Club may fly under the radar, but insiders know it''s one of the best-kept secrets in American golf—superb routing and conditioning.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Piping Rock Club', 'United States', 'New York', 'North America', NULL, 57, 'Piping Rock, designed by C.B. Macdonald in 1911, competes with polo for attention on Long Island—but holds its own with an all-world set of template holes.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Gozzer Ranch Golf & Lake Club', 'United States', 'Idaho', 'North America', NULL, 58, 'Gozzer Ranch''s setting is jaw-dropping. Perched above Lake Coeur d''Alene, it combines drama, elevation, and lakeside beauty into one unforgettable package.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Shadow Creek', 'United States', 'Nevada', 'North America', NULL, 59, 'Shadow Creek is pure Las Vegas spectacle—Tom Fazio sculpted it from desert floor to create a lush, surreal golf oasis that''s now open to all.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Scioto Country Club', 'United States', 'Ohio', 'North America', NULL, 60, 'Scioto Country Club is where Jack Nicklaus grew up and learned the game—a historic, revered place with a proud legacy and strong Midwestern spirit.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),

-- Courses 61-72
('Muirfield Village Golf Club', 'United States', 'Ohio', 'North America', NULL, 61, 'No expense was spared at Muirfield Village, and it shows. Jack Nicklaus''s vision includes water, tight fairways, and tournament-level conditioning throughout.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Plainfield Country Club', 'United States', 'New Jersey', 'North America', NULL, 62, 'Plainfield Country Club is far from plain. Donald Ross''s masterwork in New Jersey surprises many with its bold greens and thrilling, hilly terrain.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pasatiempo Golf Club', 'United States', 'California', 'North America', NULL, 63, 'Pasatiempo is vintage MacKenzie. Built in 1929, it''s got quirky charm, bold design, and a historic foursomes match to its name.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('White Bear Yacht Club', 'United States', 'Minnesota', 'North America', NULL, 64, 'White Bear Yacht Club tests your balance more than your distance. With almost no level lies, it''s a fascinating challenge requiring total control.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Monterey Peninsula Country Club (Dunes)', 'United States', 'California', 'North America', NULL, 65, 'The Dunes Course at Monterey Peninsula Country Club combines Raynor roots with MacKenzie tweaks and a modern Fazio revamp—history and progress in one.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('TPC Sawgrass (Stadium)', 'United States', 'Florida', 'North America', NULL, 66, 'TPC Sawgrass Stadium Course needs no introduction. The island green 17th has captured imaginations and shattered scorecards since 1980.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Valley Club of Montecito', 'United States', 'California', 'North America', NULL, 67, 'The Valley Club of Montecito is modest by MacKenzie standards, but its elegance and pace of play make it one of the West Coast''s most charming rounds.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Kittansett Club', 'United States', 'Massachusetts', 'North America', NULL, 68, 'The Kittansett Club''s windswept location on Buzzards Bay ensures every shot counts. Great design meets Mother Nature on this coastal New England gem.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Boston Golf Club', 'United States', 'Massachusetts', 'North America', NULL, 69, 'Boston Golf Club is routed across prime Massachusetts land. Brian Silva''s design is rugged, smart, and perfectly suited to private, pure golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Baltimore Country Club (East)', 'United States', 'Maryland', 'North America', NULL, 70, 'Baltimore CC''s East Course, designed by A.W. Tillinghast in 1926, holds true to classic architecture—historic, tough, and wonderfully tree-lined.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Milwaukee Country Club', 'United States', 'Wisconsin', 'North America', NULL, 71, 'Milwaukee Country Club is Wisconsin golf royalty. With origins dating to 1890, today''s course by Charles Hugh Alison remains a stern and scenic test.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Lawsonia (Links)', 'United States', 'Wisconsin', 'North America', NULL, 72, 'Lawsonia Links, built in 1930, is a Langford gem—bold shaping, clever bunkering, and a golden-age feel that punches well above its price tag.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop');
