
-- Complete the USA Top 100 courses migration (courses 73-100)
INSERT INTO public.golf_courses (name, country, region, continent, global_rank, usa_rank, description, thumbnail_image) VALUES
-- Courses 73-80
('Olympic Club (Lake)', 'United States', 'California', 'North America', NULL, 73, 'The Lake Course at Olympic Club is a major test. With a relentless slope and narrow fairways, it''s hosted four US Opens and deserves every one.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Nanea', 'United States', 'Hawaii', 'North America', NULL, 74, 'Nanea Golf Club in Hawaii is ultra-private and volcano-born. British links principles meet lava rock for a one-of-a-kind golfing experience.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Sand Valley Golf Resort (Sand Valley)', 'United States', 'Wisconsin', 'North America', NULL, 75, 'Sand Valley is Keiser''s inland marvel. Set on ancient dunes in Wisconsin, it feels oceanside even without the sea—sand, width, and wind in spades.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Victoria National Golf Club', 'United States', 'Indiana', 'North America', NULL, 76, 'Carved from a reclaimed coal mine, Victoria National emerged in 1997 as a vision realised by Tom Fazio and founder Terry Friedman. It''s now one of Indiana''s standout layouts—bold, dramatic, and beautifully reimagined.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Congaree Golf Club', 'United States', 'South Carolina', 'North America', NULL, 77, 'A club unlike any other, Congaree combines elite course architecture with a purpose-driven mission. Built by two experienced private club owners, this South Carolina gem is philanthropic golf at its finest.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Creek', 'United States', 'New York', 'North America', NULL, 78, 'Designed by the legendary duo Charles Blair Macdonald and Seth Raynor, The Creek is a masterclass in early American course design, blending strategic brilliance with elegant shaping.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Calusa Pines Golf Club', 'United States', 'Florida', 'North America', NULL, 79, 'Calusa Pines is bold by design—quite literally. Tons of rock were removed to give this Naples, Florida course its rare elevation changes and thrilling visual drama.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('St Louis Country Club', 'United States', 'Missouri', 'North America', NULL, 80, 'Nestled just outside the city, Saint Louis Country Club dates back to 1914 and uses its compact site creatively, showcasing the architectural subtleties of its golden-era roots.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),

-- Courses 81-90
('Ridgewood Country Club (East & West)', 'United States', 'New Jersey', 'North America', NULL, 81, 'Featuring three nine-hole loops—West, East, and Center—this club in New Jersey offers versatility and charm. The Clifford Wendehack-designed clubhouse adds historic appeal to a timeless layout.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bel-Air Country Club', 'United States', 'California', 'North America', NULL, 82, 'This George C. Thomas classic channels the glamour of the 1920s with routing that weaves through canyons and ridges. Tom Doak has called it one of the most extraordinary routings ever created.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Ladera Golf Club', 'United States', 'California', 'North America', NULL, 83, 'A minimalist contrast to nearby desert developments, this exclusive design by Gil Hanse and Jim Wagner delivers a natural, understated experience amid Palm Springs'' sculpted excess.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Honors Course', 'United States', 'Tennessee', 'North America', NULL, 84, 'Hidden in a lush valley north of Chattanooga, The Honors Course is a true Southern treasure—quietly exceptional and consistently ranked among the country''s best.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Colorado Golf Club', 'United States', 'Colorado', 'North America', NULL, 85, 'Opened in 2007, this Bill Coore and Ben Crenshaw design respects the game''s roots while embracing Colorado''s rolling terrain. It''s already considered a modern American classic.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Kingsley Club', 'United States', 'Michigan', 'North America', NULL, 86, 'Set in sandy Michigan terrain, Kingsley delivers a links-style feel far from the coast. Since opening in 2001, it has quietly built a cult following among design purists.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pikewood National Golf Club', 'United States', 'West Virginia', 'North America', NULL, 87, 'Built over years with no compromise, Pikewood is a true test of endurance and precision, winding through forested mountains on a challenging limestone landscape.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Tree Farm', 'United States', 'South Carolina', 'North America', NULL, 88, 'Born from Zac Blair''s passion for golf architecture, The Tree Farm is a modern community-focused club, designed as a place where golf lovers gather, play, and enjoy great design.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Lake Merced Golf Club', 'United States', 'California', 'North America', NULL, 89, 'This San Francisco-area course has been reshaped through the decades by MacKenzie, Graves, and Rees Jones—resulting in a course with deep architectural pedigree.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Old Elm Club', 'United States', 'Illinois', 'North America', NULL, 90, 'A collaboration between Harry Colt and Donald Ross, Old Elm is a rare blend of two great minds. Laid out in 1913, it remains a model of subtlety and traditional elegance.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),

-- Courses 91-100
('Congressional Country Club (Blue)', 'United States', 'Maryland', 'North America', NULL, 91, 'Opened in 1924, this club near Washington, D.C. began with a straightforward layout by Devereux Emmet but evolved into one of America''s most recognisable tournament venues.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Scottsdale National Golf Club (The Other Course)', 'United States', 'Arizona', 'North America', NULL, 92, 'Jackson and Khan''s 15-month effort resulted in something boldly different. With unique features and views, this course challenges conventions in the Arizona desert.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Moraine Country Club', 'United States', 'Ohio', 'North America', NULL, 93, 'Originally laid out by Alec "Nipper" Campbell in 1930, Moraine was revitalised in 2015 by Keith Foster, restoring the rolling, golden-age design that makes it so special.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Lost Rail Golf Club', 'United States', 'Nebraska', 'North America', NULL, 94, 'Scott Hoffman and his cousin teamed up with Landscapes Unlimited to create Nebraska''s next big golf destination—designed to blend top-tier construction with Midwestern soul.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Streamsong Red', 'United States', 'Florida', 'North America', NULL, 95, 'Of all the holes at Streamsong, the Red''s short par-4 9th may be the most revered—especially by Tom Doak, who considers it one of his personal favourites.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Chambers Bay', 'United States', 'Washington', 'North America', NULL, 96, 'Opened in 2007, this Washington layout has already hosted a U.S. Open and continues to rise in esteem. Built on a reclaimed gravel mine, it''s rugged and visually striking.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Fox Chapel Golf Club', 'United States', 'Pennsylvania', 'North America', NULL, 97, 'A hidden gem in Pittsburgh, Fox Chapel is one of Seth Raynor''s most underappreciated works—a course full of bold strategy and template hole precision.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Sand Valley (Sedge Valley)', 'United States', 'Wisconsin', 'North America', NULL, 98, 'Tom Doak''s Sedge Valley pays homage to the heathlands of England. Shorter than its resort siblings, it''s full of charm, character, and creative shotmaking.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Medinah Country Club (No.3)', 'United States', 'Illinois', 'North America', NULL, 99, 'A Chicago institution since the 1920s, Medinah was born from a dream to be the finest club in the country. With multiple courses, it remains a pillar of American golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bandon Dunes Golf Resort (Old Macdonald)', 'United States', 'Oregon', 'North America', NULL, 100, 'Inspired by Charles Blair Macdonald''s design principles, Old Macdonald is the fourth course at Bandon Dunes—and a bold, open tribute to early American golf ideals.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop');
