
-- Insert GB&I courses with proper country mappings
INSERT INTO public.golf_courses (name, country, region, continent, global_rank, regional_rank, description, thumbnail_image) VALUES
('Royal County Down (Championship)', 'Northern Ireland', 'Down', 'Europe', 3, 1, 'Nestled beneath the Mourne Mountains in a charming seaside town, this breathtaking links course delivers a spectacular blend of setting and strategy.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('St Andrews Links (Old)', 'Scotland', 'Fife', 'Europe', 7, 2, 'No course captures golf''s heritage quite like this one. Having hosted the Open more than any other, its fairways echo with the footsteps of legends.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Royal Portrush Golf Club (Dunluce)', 'Northern Ireland', 'Antrim', 'Europe', 9, 3, 'Perched beside a crumbling medieval castle, this dramatic coastal links demands precision—and rewards it with unforgettable views and challenge.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Muirfield - Honourable Company of Edinburgh Golfers', 'Scotland', 'Lothians', 'Europe', 10, 4, 'The oldest club in the world still thrives today on this storied layout, designed for strategy and shotmaking, with history underfoot at every turn.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Trump Turnberry Resort - Ailsa', 'Scotland', 'Ayrshire & Arran', 'Europe', 12, 5, 'Overlooking the Firth of Clyde, this Open venue may be the most visually striking of them all—majestic, dramatic, and endlessly scenic.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Royal Dornoch Golf Club (Championship)', 'Scotland', 'North Scotland', 'Europe', 15, 6, 'Timeless and remote, this northern masterpiece has an almost mystical quality, captivating amateurs and pros alike.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Royal St George''s Golf Club', 'England', 'Kent', 'Europe', 19, 7, 'This course stands out for its natural rhythm—undisturbed, rugged, and undeniably authentic.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Sunningdale Golf Club (Old)', 'England', 'Surrey', 'Europe', 22, 8, 'Set among mature trees and undulating ground, this inland layout is often called the most beautiful of its kind in the British Isles.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Ballybunion Golf Club (Old)', 'Ireland', 'Kerry', 'Europe', 29, 9, 'Approaching from the coastal road, it''s impossible not to be awed by the sweeping links land that stretches to the Atlantic.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Lahinch Golf Club (Old)', 'Ireland', 'Clare', 'Europe', 32, 10, 'Laid along the bay, this course combines rustic charm with tough shot values and a spirited seaside breeze.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Carnoustie Golf Links (Championship)', 'Scotland', 'Angus & Dundee', 'Europe', 34, 11, 'With its gnarly bunkers and windswept fairways, this classic links layout is both raw and brutally demanding.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Rosapenna Golf Resort - St Patrick''s Links', 'Ireland', 'Donegal', 'Europe', 37, 12, 'Built in 2020, this bold coastal design from a modern master has already made its mark in the world of contemporary links golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Sunningdale Golf Club (New)', 'England', 'Surrey', 'Europe', 41, 13, 'Paired together, these two sister courses offer a sublime 36-hole experience—a blend of elegance and challenge.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('North Berwick Golf Club (West Links)', 'Scotland', 'Lothians', 'Europe', 42, 14, 'With sea views throughout and clever green sites, this course delivers both charm and shotmaking joy.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Kingsbarns Golf Links', 'Scotland', 'Fife', 'Europe', 43, 15, 'This newer layout hugs the shoreline, delivering panoramic views and thoughtful design with each hole.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Ardfin', 'Scotland', 'Argyll & Bute', 'Europe', 44, 16, 'Dramatically routed along rocky cliffs, this remote course is a feast for the eyes and a test for any golfer.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('St Enodoc Golf Club (Church)', 'England', 'Cornwall', 'Europe', 49, 17, 'Full of personality, this lively course winds through dunes and ridges, with a local flair all its own.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Swinley Forest Golf Club', 'England', 'Berkshire', 'Europe', 52, 18, 'A throwback gem on sandy soil, this old-school design remains timeless—unchanged, unhurried, and unforgettable.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Cabot Highlands Castle Stuart', 'Scotland', 'North Scotland', 'Europe', 54, 19, 'Set along the Moray coast, this course brings modern flair to Scotland''s Highland tradition.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Royal Lytham & St Annes Golf Club', 'England', 'Lancashire', 'Europe', 61, 20, 'The northernmost English championship layout, this coastal test is pure, unfiltered links golf.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Royal Porthcawl Golf Club', 'Wales', 'South Wales', 'Europe', 65, 21, 'Wales'' flagship course impresses with championship character and natural seclusion—it''s a hidden treasure.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Cruden Bay Golf Club (Championship)', 'Scotland', 'North East Scotland', 'Europe', 70, 22, 'This captivating course winds through dunes with unpredictable flair—loved by purists and adventurers alike.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Ganton Golf Club', 'England', 'Yorkshire', 'Europe', 72, 23, 'Once a sea inlet, now a sandy inland course with echoes of classic links and heathland strategy.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Portmarnock Golf Club (Championship)', 'Ireland', 'Dublin', 'Europe', 74, 24, 'Some of the finest finishing holes anywhere, combining wind, views, and pure design brilliance.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Trump International Golf Links Scotland - Old Course', 'Scotland', 'North East Scotland', 'Europe', 77, 25, 'Spanning three miles of exposed coastline, this bold modern layout serves up stunning views and serious shot-making.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Royal Birkdale Golf Club', 'England', 'Lancashire', 'Europe', 82, 26, 'Much-loved on the major championship rota, this links track is famed for its fair test and unrelenting quality.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('St George''s Hill Golf Club (Red & Blue)', 'England', 'Surrey', 'Europe', 85, 27, 'One glance from the clubhouse and you''re met with a scene that stirs every golfer''s soul.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Royal Aberdeen Golf Club (Balgownie)', 'Scotland', 'North East Scotland', 'Europe', 88, 28, 'A classic links with a dramatic front nine that rolls out beside the crashing North Sea.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Royal Cinque Ports Golf Club', 'England', 'Kent', 'Europe', 90, 29, 'Rugged and raw, this coastal brute offers an exhilarating ride from first tee to final green.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Prestwick Golf Club', 'Scotland', 'Ayrshire & Arran', 'Europe', 93, 30, 'Steeped in history, this bumpy stretch of dunes delivers golf as it was played generations ago.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),

-- GB&I courses with only regional rankings (31-100)
('West Sussex Golf Club', 'England', 'Sussex', 'Europe', NULL, 31, 'Tucked into a sandy heath, this inland gem plays firm and fast with undeniable charm.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Rye Golf Club (Old)', 'England', 'Sussex', 'Europe', NULL, 32, 'One of Britain''s toughest challenges, this course demands precision and celebrates golden-age design.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Woodhall Spa Golf Club (Hotchkin)', 'England', 'Lincolnshire', 'Europe', NULL, 33, 'With towering trees and natural contours, this secluded haven is a delight to both walk and play.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Royal Troon Golf Club (Old)', 'Scotland', 'Ayrshire & Arran', 'Europe', NULL, 34, 'Beloved by traditionalists, this course is known for its unforgettable short holes and clever routing.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Royal West Norfolk Golf Club', 'England', 'Norfolk', 'Europe', NULL, 35, 'Cut off by high tides, this isolated links has a wild, untamed character you won''t soon forget.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Walton Heath Golf Club (Old)', 'England', 'Surrey', 'Europe', NULL, 36, 'Although landlocked, this inland track has the soul and rhythm of a true seaside links.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Machrihanish Golf Club (Championship)', 'Scotland', 'Argyll & Bute', 'Europe', NULL, 37, 'Short and sweet, this scenic spot offers quirky charm and strategic thrills in equal measure.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Royal Liverpool Golf Club', 'England', 'Cheshire', 'Europe', NULL, 38, 'Exposed to strong coastal winds, this no-frills links demands creativity and control.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Gleneagles (King''s)', 'Scotland', 'Perth & Kinross', 'Europe', NULL, 39, 'Framed by rolling hills, this majestic layout boasts grandeur, challenge, and spectacular views.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Loch Lomond Golf Club', 'Scotland', 'Dunbartonshire', 'Europe', NULL, 40, 'With loch views and mountain backdrops, this secluded retreat exudes natural beauty and scale.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Alwoodley Golf Club', 'England', 'Yorkshire', 'Europe', NULL, 41, 'Unassuming yet refined, this rural gem is known for its subtle design and whisper-quiet surroundings.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('European Club', 'Ireland', 'Wicklow', 'Europe', NULL, 42, 'Located on a rugged Irish coastline, this flowing layout serves up postcard views and classic links traits.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Western Gailes Golf Club', 'Scotland', 'Ayrshire & Arran', 'Europe', NULL, 43, 'Winding through heather and burns, this moody layout is big on character and variety.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Hollinwell', 'England', 'Nottinghamshire', 'Europe', NULL, 44, 'Quiet and private, this sandy heathland design rewards patience and smart play.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Waterville Golf Links', 'Ireland', 'Kerry', 'Europe', NULL, 45, 'Clinging to the edge of land and sea, this coastal masterpiece offers relentless views and shot values.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Dumbarnie Links', 'Scotland', 'Fife', 'Europe', NULL, 46, 'Sweeping vistas and wide fairways define this modern build, laid atop a storied estate.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Silloth on Solway Golf Club', 'England', 'Cumbria', 'Europe', NULL, 47, 'Off the beaten path, this course is rugged, wind-swept, and rich in authentic links texture.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Island', 'Ireland', 'Dublin', 'Europe', NULL, 48, 'Rough around the edges in all the right ways, this rustic gem channels the game''s early roots.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Berkshire Golf Club (Red)', 'England', 'Berkshire', 'Europe', NULL, 49, 'Lined with forests and full of bounce, this inland layout is pure joy in every season.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('County Louth Golf Club', 'Ireland', 'Louth', 'Europe', NULL, 50, 'With a road to the clubhouse nearly as memorable as the course itself, this links exudes charm.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Hillside Golf Club', 'England', 'Lancashire', 'Europe', NULL, 51, 'A lesser-known neighbour to a famed venue, this hidden gem punches well above its weight.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Formby Golf Club', 'England', 'Lancashire', 'Europe', NULL, 52, 'A pine-fringed blend of heath and linksland, perfect for golfers who love variety and texture.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Saunton Golf Club (East)', 'England', 'Devon', 'Europe', NULL, 53, 'Championship-calibre and Open-ready, this firm, fast test is one of the country''s finest.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Nairn Golf Club (Championship)', 'Scotland', 'North Scotland', 'Europe', NULL, 54, 'Few courses rival this one for seaside drama—every hole is a photo op waiting to happen.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Wentworth Club (West)', 'England', 'Surrey', 'Europe', NULL, 55, 'The flagship of inland golf in its region, this is a bold, testing track full of character.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Hankley Common Golf Club', 'England', 'Surrey', 'Europe', NULL, 56, 'Spacious, strategic, and wonderfully walkable, this inland design balances width with demand.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('County Sligo Golf Club (Championship)', 'Ireland', 'Sligo', 'Europe', NULL, 57, 'Dramatically positioned above the sea, this is a stirring west-coast adventure from start to finish.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Trump International Golf Links - Ireland', 'Ireland', 'Clare', 'Europe', NULL, 58, 'Once crafted by a legend, now revitalised into a visual and tactical tour de force.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Another Place, The Machrie', 'Scotland', 'Argyll & Bute', 'Europe', NULL, 59, 'Rustic and untamed, this windblown outpost beside a boutique hotel offers golf at its purest.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Adare Manor Golf Club', 'Ireland', 'Limerick', 'Europe', NULL, 60, 'Luxurious and bold, this parkland stage is set to welcome a Ryder Cup in style.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Gullane Golf Club (No.1)', 'Scotland', 'Lothians', 'Europe', NULL, 61, 'Meticulously conditioned and scenic, this winter-friendly track is loved for its year-round appeal.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Burnham & Berrow Golf Club (Championship)', 'England', 'Somerset', 'Europe', NULL, 62, 'A historic tournament venue that continues to test elite players on every visit.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Carne Golf Links (Wild Atlantic Dunes)', 'Ireland', 'Mayo', 'Europe', NULL, 63, 'This massive dunescape feels like another world—raw, windswept, and unforgettable.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Ballyliffin Golf Club (Glashedy Links)', 'Ireland', 'Donegal', 'Europe', NULL, 64, 'A northern outpost that impresses with its wild terrain and rolling dunes.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Rosapenna (Sandy Hills Links)', 'Ireland', 'Donegal', 'Europe', NULL, 65, 'Built on bold elevation and strategic design, this course is a thrilling journey from start to finish.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Woking Golf Club', 'England', 'Surrey', 'Europe', NULL, 66, 'A charming heathland venue with character, quirk, and an unmistakable sense of history.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Tralee Golf Club', 'Ireland', 'Kerry', 'Europe', NULL, 67, 'Panoramic coastal views meet clever shot-making on this beautifully sculpted seaside layout.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Queenwood Golf Club', 'England', 'Surrey', 'Europe', NULL, 68, 'Pristine and private, this refined destination oozes exclusivity and polish.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Hunstanton Golf Club', 'England', 'Norfolk', 'Europe', NULL, 69, 'An under-the-radar coastal gem, full of charm and memorable holes by the sea.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Enniscrone Golf Club (Dunes)', 'Ireland', 'Sligo', 'Europe', NULL, 70, 'Carved through massive dunes, this epic course delivers drama, scale, and soul.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Liphook Golf Club', 'England', 'Hampshire', 'Europe', NULL, 71, 'For fans of traditional golf, this classic heathland layout is an absolute treat.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Worplesdon Golf Club', 'England', 'Surrey', 'Europe', NULL, 72, 'Refined, scenic, and always in perfect condition, this is the crown jewel of the Three Ws.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Skibo Castle - Carnegie Links', 'Scotland', 'North Scotland', 'Europe', NULL, 73, 'Luxurious and grand, this storybook layout brings together sweeping views and top-tier conditioning.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('The Renaissance Club', 'Scotland', 'Lothians', 'Europe', NULL, 74, 'Modern in vision but classic in execution, this is a contemporary masterpiece of golf architecture.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Old Head Golf Links', 'Ireland', 'Cork', 'Europe', NULL, 75, 'Jutting far into the sea, this dramatic clifftop venue offers one of the most thrilling experiences in the game.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Portstewart Golf Club (Strand)', 'Northern Ireland', 'Londonderry', 'Europe', NULL, 76, 'Rolling through vast dunes, this visually spectacular course is as fun as it is photogenic.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('West Hill Golf Club', 'England', 'Surrey', 'Europe', NULL, 77, 'Short, compact, and full of life—this charming heathland course is packed with character.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Narin and Portnoo Links', 'Ireland', 'Donegal', 'Europe', NULL, 78, 'Wild, raw, and remote, this is pure links golf on nature''s terms.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pennard Golf Club', 'Wales', 'South Wales', 'Europe', NULL, 79, 'Set high above the coastline, this elevated course is both challenging and unforgettable.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Gleneagles (Queen''s)', 'Scotland', 'Perth & Kinross', 'Europe', NULL, 80, 'Though shorter in length, this royal companion to a bigger sibling is elegant and strategic.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Royal St David''s Golf Club', 'Wales', 'North Wales', 'Europe', NULL, 81, 'Backed by a medieval castle and wrapped in towering dunes, this is one of Wales'' treasures.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Machrihanish Dunes', 'Scotland', 'Argyll & Bute', 'Europe', NULL, 82, 'Left as untouched as possible, this links is all about simplicity, rhythm, and beauty.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('Parkstone Golf Club', 'England', 'Dorset', 'Europe', NULL, 83, 'Seaside views meet inland pine with excellent elevation and variety across the routing.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Berkshire Golf Club (Blue)', 'England', 'Berkshire', 'Europe', NULL, 84, 'Winding through woodlands, this shorter sibling to a championship course has its own flair.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Aberdovey Golf Club', 'Wales', 'North Wales', 'Europe', NULL, 85, 'Simple, natural, and pure, this coastal links captures everything beautiful about the game.', 'https://images.uns plash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('West Lancashire Golf Club', 'England', 'Lancashire', 'Europe', NULL, 86, 'Flanked by bigger names, this lesser-known layout is just as deserving of top billing.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Prince''s Golf Club (Shore & Dunes)', 'England', 'Kent', 'Europe', NULL, 87, 'With deep Open Championship roots, this links is rich in heritage and rolling contours.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('The Addington Golf Club', 'England', 'Surrey', 'Europe', NULL, 88, 'An inland retreat full of springy turf and blooming heath, as charming as it is playable.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Broadstone Golf Club', 'England', 'Dorset', 'Europe', NULL, 89, 'This countryside escape offers hilly drama and endless views over the landscape.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('JCB Golf & Country Club', 'England', 'Staffordshire', 'Europe', NULL, 90, 'A bold and futuristic build, this mega-modern layout is unlike anything else in the UK.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Hindhead Golf Club', 'England', 'Surrey', 'Europe', NULL, 91, 'With rugged elevation and a tale of two terrains, this course brings the Ice Age to life.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Walton Heath Golf Club (New)', 'England', 'Surrey', 'Europe', NULL, 92, 'Set beside its storied sibling, this inland design is tough, narrow, and endlessly engaging.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Castletown Golf Links', 'Isle of Man', 'Isle of Man', 'Europe', NULL, 93, 'Nearly surrounded by ocean, this headland course brings visual drama to every hole.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Delamere Forest Golf Club', 'England', 'Cheshire', 'Europe', NULL, 94, 'A golden-age gem that flows beautifully through undulating heathland terrain.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Southport & Ainsdale Golf Club', 'England', 'Lancashire', 'Europe', NULL, 95, 'Younger in age but mature in challenge, this course brings serious links pedigree.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Moortown Golf Club', 'England', 'Yorkshire', 'Europe', NULL, 96, 'Soft underfoot but hard to score on, this moorland design is rich in charm and character.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Wallasey Golf Club', 'England', 'Cheshire', 'Europe', NULL, 97, 'Unpolished, windswept, and full of quirks, this links remains true to the game''s roots.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Royal Dublin Golf Club', 'Ireland', 'Dublin', 'Europe', NULL, 98, 'Routing through shifting sands, this layout is perfectly suited to its island setting.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Brora Golf Club', 'Scotland', 'North Scotland', 'Europe', NULL, 99, 'With weathered dunes and Highland air, this rustic links offers timeless simplicity.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),
('St Andrews Links (New)', 'Scotland', 'Fife', 'Europe', NULL, 100, 'Often overlooked, this tighter local''s favourite is a pure golfing test from start to finish.', 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop'),

-- USA courses
('Cypress Point Club', 'United States', 'California', 'North America', 1, NULL, 'Cypress Point stuns with dramatic coastal terrain where the Santa Lucia Mountains meet the Pacific. Every hole offers exhilarating elevation changes and panoramic ocean views.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pine Valley Golf Club', 'United States', 'New Jersey', 'North America', 2, NULL, 'Pine Valley is George Crump''s legacy to the game—unforgiving, strategic, and brilliantly executed. Widely regarded as the pinnacle of penal golf architecture.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Shinnecock Hills Golf Club', 'United States', 'New York', 'North America', 4, NULL, 'Shinnecock Hills holds a unique place in golf history, not only for its role in founding the USGA but also as the site of one of the first purpose-built clubhouses.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('National Golf Links of America', 'United States', 'New York', 'North America', 5, NULL, 'National Golf Links of America is a masterpiece of early 20th-century design—part tribute, part benchmark for modern architects, and all classic charm.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Oakmont Country Club', 'United States', 'Pennsylvania', 'North America', 8, NULL, 'Oakmont is as brutal as it is brilliant. A beast of a course that''s hosted more majors than any in the U.S. outside Augusta—and tests the best every time.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Sand Hills Golf Club', 'United States', 'Nebraska', 'North America', 11, NULL, 'Sand Hills offers a spiritual kind of golf—a course built on simplicity, natural design, and a proud resistance to commercial fanfare.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Merion Golf Club (East)', 'United States', 'Pennsylvania', 'North America', 13, NULL, 'Merion may be old, but it''s far from outdated. This Philadelphia gem evolved from cricket-playing roots to host some of the game''s most storied moments.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Augusta National Golf Club', 'United States', 'Georgia', 'North America', 16, NULL, 'Augusta National is where golf''s finest minds met perfection. Jones and MacKenzie created more than just a course—they created legend.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Los Angeles Country Club (North)', 'United States', 'California', 'North America', 18, NULL, 'Los Angeles Country Club''s North Course lives up to its postcode. Elegant, exclusive, and architecturally rich—it''s a course that matches its prestigious setting.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Fishers Island Club', 'United States', 'New York', 'North America', 20, NULL, 'Fishers Island Club is a coastal gem—remote and romantic. Playing here feels like stepping into a time capsule lined with ocean spray.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Friar''s Head', 'United States', 'New York', 'North America', 23, NULL, 'Friar''s Head is Coore and Crenshaw at their most creative. Carved from rugged land, this course champions freedom, imagination, and playability.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Chicago Golf Club', 'United States', 'Illinois', 'North America', 24, NULL, 'Chicago Golf Club is steeped in legacy. One of America''s earliest clubs, and still one of its most elusive—tradition reigns supreme here.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bandon Dunes Golf Resort (Pacific Dunes)', 'United States', 'Oregon', 'North America', 26, NULL, 'Pacific Dunes is Tom Doak''s standout at Bandon—raw, rugged, and endlessly captivating. Many would argue it''s the best of the lot.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pebble Beach Golf Links', 'United States', 'California', 'North America', 27, NULL, 'Pebble Beach is the accessible cousin to Cypress—every bit as scenic, with a history and layout that speaks for itself.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Prairie Dunes Country Club', 'United States', 'Kansas', 'North America', 28, NULL, 'Prairie Dunes surprises many. It''s Kansas, but it feels coastal. Inland links golf doesn''t get more authentic than this.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Riviera Country Club', 'United States', 'California', 'North America', 30, NULL, 'Riviera''s tight terrain and brilliant bunkering make it a rare gem. A strategic layout that gets better the more you play it.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Crystal Downs Country Club', 'United States', 'Michigan', 'North America', 31, NULL, 'Crystal Downs blends MacKenzie artistry with Midwest charm. A subtle headland course that rewards the observant and punishes the reckless.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Winged Foot Golf Club (West)', 'United States', 'New York', 'North America', 33, NULL, 'Winged Foot (West) is Tillinghast at his finest—relentless, clever, and unforgiving. A true test of championship mettle.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('California Golf Club of San Francisco (Cal Club)', 'United States', 'California', 'North America', 36, NULL, 'Cal Club stretches out with purpose and punch. The modernised layout now plays long and tough, making it worthy of today''s top competitions.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Old Town Club', 'United States', 'North Carolina', 'North America', 38, NULL, 'Perry Maxwell''s design at Old Town Club showcases how undulating terrain can be transformed into a masterpiece. The steep swales and sharply contoured greens offer a thrilling challenge from start to finish.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('San Francisco Golf Club', 'United States', 'California', 'North America', 39, NULL, 'Crafted in 1915 by A.W. Tillinghast, San Francisco Golf Club is a true work of genius. Every hole is a testament to his architectural brilliance, wrapped in tradition and timeless design.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Somerset Hills Country Club', 'United States', 'New Jersey', 'North America', 40, NULL, 'Somerset Hills is a course of two contrasting natures: flat and open on the outward nine, then morphing into tight, wooded terrain on the inward holes—each with its own distinct charm.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Oakland Hills Country Club (South)', 'United States', 'Michigan', 'North America', 46, NULL, 'Oakland Hills'' South Course is steeped in championship history. With tree-lined fairways, formidable length, and six U.S. Opens under its belt, it''s a layout that demands both precision and power.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Camargo Club', 'United States', 'Ohio', 'North America', 48, NULL, 'Camargo Club, a Seth Raynor creation, is nestled in the rolling Ohio countryside. With its signature template holes and understated elegance, it''s one of America''s great hidden treasures.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Shoreacres', 'United States', 'Illinois', 'North America', 51, NULL, 'A visit to Shoreacres feels like stepping back into the golden age of golf. The David Adler-designed clubhouse and elegant layout combine to create a time-capsule experience.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('CapRock Ranch', 'United States', 'Nebraska', 'North America', 53, NULL, 'CapRock Ranch, perched in Nebraska''s sand hills, is the latest must-play destination for those chasing adventure and seclusion—golf here is rugged, remote and unforgettable.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Seminole Golf Club', 'United States', 'Florida', 'North America', 55, NULL, 'Located along Florida''s Atlantic coast, Seminole Golf Club is revered for its routing. The seamless way the course flows with the land is a masterclass in strategic architecture.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Pinehurst (No.2)', 'United States', 'North Carolina', 'North America', 57, NULL, 'Pinehurst No.2 is golf''s ultimate test of precision. Opened in 1907, its turtleback greens and subtle defenses define Donald Ross''s genius.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop'),
('Bethpage (Black)', 'United States', 'New York', 'North America', 58, NULL, 'Bethpage Black is as tough as they come. With its brutal slope rating, narrow fairways and thick rough, it''s not for the timid—this course is all about survival.', 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=400&h=300&fit=crop');

-- Add USA rankings to the USA courses
UPDATE public.golf_courses SET usa_rank = 1 WHERE name = 'Cypress Point Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 2 WHERE name = 'Pine Valley Golf Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 3 WHERE name = 'Shinnecock Hills Golf Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 4 WHERE name = 'National Golf Links of America' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 5 WHERE name = 'Oakmont Country Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 6 WHERE name = 'Sand Hills Golf Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 7 WHERE name = 'Merion Golf Club (East)' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 8 WHERE name = 'Augusta National Golf Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 9 WHERE name = 'Los Angeles Country Club (North)' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 10 WHERE name = 'Fishers Island Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 11 WHERE name = 'Friar''s Head' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 12 WHERE name = 'Chicago Golf Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 13 WHERE name = 'Bandon Dunes Golf Resort (Pacific Dunes)' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 14 WHERE name = 'Pebble Beach Golf Links' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 15 WHERE name = 'Prairie Dunes Country Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 16 WHERE name = 'Riviera Country Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 17 WHERE name = 'Crystal Downs Country Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 18 WHERE name = 'Winged Foot Golf Club (West)' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 19 WHERE name = 'California Golf Club of San Francisco (Cal Club)' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 20 WHERE name = 'Old Town Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 21 WHERE name = 'San Francisco Golf Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 22 WHERE name = 'Somerset Hills Country Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 23 WHERE name = 'Oakland Hills Country Club (South)' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 24 WHERE name = 'Camargo Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 25 WHERE name = 'Shoreacres' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 26 WHERE name = 'CapRock Ranch' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 27 WHERE name = 'Seminole Golf Club' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 28 WHERE name = 'Bethpage (Black)' AND country = 'United States';
UPDATE public.golf_courses SET usa_rank = 29 WHERE name = 'Pinehurst (No.2)' AND country = 'United States';
